version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: internal-print-service-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    restart: unless-stopped
